### ISSUE TITLE
50系显卡报错

### ISSUE THREAD

**Issue by Chopin68** [warmshao/FasterLivePortrait#181]
目前整合包和docker都试过，都是类似错误

/root/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py:173: UserWarning:
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/ge
t-started/locally/

在执行all_onnx2trt.bat的时候，
也会出现没办法转换的情况
C:\baidunetdiskdownload\program\FasterLivePortrait-windows-20241228\FasterLivePortrait-windows\scripts\onnx2trt.py:61: DeprecationWarning: Use set_memory_pool_limit instead.
  self.config.max_workspace_size = 12 * (2 ** 30)  # 12 GB
[06/25/2025-02:23:24] [TRT] [I] No importer registered for op: GridSample3D. Attempting to import as plugin.
[06/25/2025-02:23:24] [TRT] [I] Searching for plugin: GridSample3D, plugin_version: 1, plugin_namespace:
paddingMode: 0
interpolationMode: 0
[06/25/2025-02:23:24] [TRT] [I] Successfully created plugin: GridSample3D
output datatype: 0
output datatype: 0
[06/25/2025-02:23:24] [TRT] [I] No importer registered for op: GridSample3D. Attempting to import as plugin.
[06/25/2025-02:23:24] [TRT] [I] Searching for plugin: GridSample3D, plugin_version: 1, plugin_namespace:
paddingMode: 0
interpolationMode: 0
[06/25/2025-02:23:24] [TRT] [I] Successfully created plugin: GridSample3D
output datatype: 0
output datatype: 0
INFO:EngineBuilder:Network Description
INFO:EngineBuilder:Input 'feature_3d' with shape (1, 32, 16, 64, 64) and dtype DataType.FLOAT
INFO:EngineBuilder:Input 'kp_driving' with shape (1, 21, 3) and dtype DataType.FLOAT
INFO:EngineBuilder:Input 'kp_source' with shape (1, 21, 3) and dtype DataType.FLOAT
INFO:EngineBuilder:Output 'out' with shape (1, 3, 512, 512) and dtype DataType.FLOAT

大佬有办法吗

**Comment by 807502278** [comment]
50系要torch2.7以上，一键包和docker的是2.4，自己整个环境就好了

**Comment by Chopin68** [comment]
> 50系要torch2.7以上，一键包和docker是2.4，自己整个环境就好了

你有成功运行了吗，虽然成功安装了torch2.7啥的，但是tensorrt引擎没办法成功构建，我猜是需要编译支持sm120的grid_sample_3d_plugin.dll才能成功推理，
但是我编译了支持sm120进行TensorrtExecutionProvider 的推理的时候会出现这种错误


2025-07-02 01:38:52.0693112 [E:onnxruntime:, sequential_executor.cc:572 onnxruntime::ExecuteKernel] Non-zero status code returned while running GridSample node. Name:'/dense_motion_network/GridSample' Status Message: Only 4-D tensor is supported

**Comment by 807502278** [comment]
我用trt原项目示例代码编译的，但是xpos编译失败了暂时只能用人物的

**Comment by Chopin68** [comment]
Resolved
